language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'

cache:
  directories:
  - 'node_modules'

env:
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="11"

before_install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  - export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - node -v && yarn -V
  - travis_retry yarn

script:
  - yarn run lint
  - yarn run test
